services:
  - type: web
    name: splitease-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate --no-input && python manage.py collectstatic --no-input
    startCommand: daphne -b 0.0.0.0 -p $PORT config.asgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: splitease-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://splitease.vercel.app
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_CDB4vVEQ5Uhd@ep-lively-union-adgs3ubm-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
