# Generated by Django 4.2.30 on 2026-06-14 08:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('left_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='groups.groupmember')),
            ],
            options={
                'db_table': 'membership_history',
                'ordering': ['joined_date'],
            },
        ),
    ]
