# Generated by Django 4.2.30 on 2026-06-14 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_membershiphistory'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending_review', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='groups.group')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('row_data', models.JSONField()),
                ('issue_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resolution_selected', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution_details', models.JSONField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='expenses.importjob')),
            ],
            options={
                'db_table': 'import_issues',
                'ordering': ['row_number'],
            },
        ),
    ]
